Hacky change to be able to only provide speedtest on localhost or lis…
jeanralphaviles/prometheus_speedtest pull request #3
Opened 2019-07-13 20:07 UTC by McChicken93

…ten to other addresses

2019-07-15 15:04 UTC, jeanralphaviles requested changes

2019-07-15 15:04 UTC, jeanralphaviles commented on prometheus_speedtest/prometheus_speedtest.py
> +    default='',
Maybe we should default this to '0.0.0.0' so its obvious that we listen on all addresses by default.

2019-07-15 15:04 UTC, jeanralphaviles commented on prometheus_speedtest/prometheus_speedtest.py
> +PARSER.add_argument(
Could you put the new output of **prometheus_speedtest --help** in the usage section of [README.md](https://github.com/jeanralphaviles/prometheus_speedtest/blob/050b234/README.md#Usage)?

2019-07-15 15:05 UTC, jeanralphaviles commented
> Hacky change....
This looks great to me, its how I would implement it. Thank you for the PR.

2019-07-15 18:01 UTC, McChicken93 commented
There you go ;)

2019-07-15 21:09 UTC, twhuhn reviewed
And it's a new feature, hence the 0.7.0

2019-07-16 01:39 UTC, jeanralphaviles requested changes
Just one nit, and then it'll be good to go.

2019-07-16 01:39 UTC, jeanralphaviles commented on README.md
> +  -a address, --address address
You missed [-a address] after [-h] in the "usage:" line

usage: prometheus_speedtest.py [-h] [-a address] [-p port] [-v]

2019-07-18 06:38 UTC, closed without merging

2019-07-18 06:43 UTC, jeanralphaviles commented
v0.7.0 has been pushed to PyPi: <https://pypi.org/project/prometheus-speedtest> and DockerHub: <https://hub.docker.com/r/jraviles/prometheus_speedtest>

Thanks for the PR.